# Generated by Django 4.2.7 on 2026-10-09 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_automationjob_verification_state'),
        ('api', '0003_user_scoped_settings_and_exports'),
    ]

    operations = [
    ]
