# Generated by Django 4.2.7 on 2026-02-06 18:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior_type', models.CharField(max_length=50)),
                ('data', models.JSONField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to='account.botaccount')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('follows_count', models.IntegerField(default=0)),
                ('unfollows_count', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('downloads_count', models.IntegerField(default=0)),
                ('profiles_explored', models.IntegerField(default=0)),
                ('stories_viewed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='account.botaccount')),
            ],
            options={
                'verbose_name_plural': 'Daily Analytics',
                'ordering': ['-date'],
                'unique_together': {('date', 'account')},
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('follow', 'Follow'), ('unfollow', 'Unfollow'), ('like', 'Like'), ('unlike', 'Unlike'), ('comment', 'Comment'), ('view_story', 'View Story'), ('download', 'Download'), ('scrape_profile', 'Scrape Profile'), ('scrape_posts', 'Scrape Posts')], max_length=30)),
                ('target_username', models.CharField(blank=True, max_length=50, null=True)),
                ('target_url', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='account.botaccount')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='account.session')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'action_type'], name='analytics_a_account_cafe5d_idx'), models.Index(fields=['created_at'], name='analytics_a_created_bca71f_idx')],
            },
        ),
    ]
