# Generated by Django 4.2.7 on 2026-02-06 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('protocol', models.CharField(default='http', max_length=10)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('failure_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Proxies',
            },
        ),
        migrations.CreateModel(
            name='BotAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_encrypted', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('banned', 'Banned'), ('checkpoint', 'Checkpoint')], default='active', max_length=20)),
                ('trust_score', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('cookies_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='api_v1_accounts.proxy')),
            ],
        ),
    ]
