name: Docker CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to AWS ECR
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1

    - name: Build and push Backend Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: backend/Dockerfile
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/insta-bot-backend:latest

    - name: Build and push Automation Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: automation/Dockerfile
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/insta-bot-automation:latest

    - name: Build and push Frontend Image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        file: frontend/Dockerfile.prod
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/insta-bot-frontend:latest
